/* ============================================
   KCW — Single source of truth
   Edit this file to add/edit projects;
   every page reads from here at runtime.
   ============================================ */

const SITE = {
  name: 'KCW',
  fullName: "Khizar's Custom Wood Work",
  tagline: 'Handcrafted woodwork and custom cabinetry for discerning homeowners across the Greater Toronto Area.',
  year: 2026,
  contact: {
    location: '100 Dynamic Drive',
    phone: '(647) 231-5177',
    phoneRaw: '+16472315177',
    email: 'khizar@k-customwoodwork.ca',
    instagramHandle: '@k_customwoodwork',
    instagramUrl: 'https://www.instagram.com/k_customwoodwork/',
  },
  nav: [
    { id: 'about',     label: 'About',     href: 'about.html' },
    { id: 'portfolio', label: 'Projects', href: 'portfolio.html' },
    { id: 'contact',   label: 'Contact',   href: 'contact.html' },
  ],
};

/* ---------- Projects (portfolio detail pages) ---------- */

const PROJECTS = {
  brimley: {
    id: 'brimley',
    eyebrow: 'Custom Home',
    detailEyebrow: 'Commercial Millwork',
    address: '3370 Brimley Rd',
    titleLong: '3370 Brimley Rd.',
    cardImage: 'assets/3370-project-images/PROJECT%20BRIMLEY%20ALBUMCOVER.jpg',
    cardContain: true,
    isCutout: false,
    heroImage: 'assets/brimley house foulder.jpg',
    cardBlurb: 'A modern two-storey residence in Scarborough — brick, stucco, and custom millwork brought together from the studs out.',
    lede: 'A full commercial fit-out in Scarborough — reception joinery, custom millwork, and finish carpentry handled end-to-end by the KCW team.',
    narrative: {
      heading: 'Project Overview',
      paragraphs: [
        'The brief at 3370 Brimley was simple on paper, complicated in execution: deliver a commercial space that reads as warm, grounded, and professional — without defaulting to the beige office-park template.',
        'KCW handled the full scope of the millwork package — reception casework, interior wood detailing, storage built-ins, and finish carpentry throughout. Every piece was milled in our shop, colour-matched to the interior scheme, and installed by the same crew that built it.',
        'The result is a space that feels tailored without feeling precious — surfaces that hold up to daily commercial traffic, details that hold up to a second look.',
      ],
    },
    specs: {
      heading: 'Project Specs',
      items: [
        { label: 'Location',   value: '3370 Brimley Rd, Scarborough ON' },
        { label: 'Scope',      value: 'Commercial millwork & finish carpentry' },
        { label: 'Materials',  value: 'Engineered veneers, solid hardwood trim' },
        { label: 'Delivered',  value: 'In-house design, mill, and install' },
        { label: 'Status',     value: 'Completed' },
      ],
    },
    cta: {
      heading: 'Planning A Commercial Fit-Out?',
      body: "Tell us the space and the brief — we'll tell you what it actually takes.",
      label: 'Start A Project',
    },
    metaDescription: 'KCW Project — 3370 Brimley Rd. Commercial millwork and finish carpentry in Scarborough.',
    gallery: [
      { type: 'image', src: 'assets/3370-project-images/1.jpg' },
      { type: 'image', src: 'assets/3370-project-images/3.5.jpg' },
      { type: 'image', src: 'assets/3370-project-images/3.jpg' },
      { type: 'image', src: 'assets/3370-project-images/4.jpg' },
      { type: 'image', src: 'assets/3370-project-images/5.jpg' },
      { type: 'image', src: 'assets/3370-project-images/6.jpg' },
      { type: 'image', src: 'assets/3370-project-images/7.jpg' },
      { type: 'image', src: 'assets/3370-project-images/8.jpg' },
      { type: 'image', src: 'assets/3370-project-images/9.jpg' },
      { type: 'image', src: 'assets/3370-project-images/9.5.jpg' },
      { type: 'image', src: 'assets/3370-project-images/10.jpg' },
      { type: 'image', src: 'assets/3370-project-images/11.jpg' },
      { type: 'image', src: 'assets/3370-project-images/13.jpg' },
      { type: 'image', src: 'assets/3370-project-images/14.jpg' },
      { type: 'image', src: 'assets/3370-project-images/15.jpg' },
      { type: 'image', src: 'assets/3370-project-images/16.jpg' },
      { type: 'image', src: 'assets/3370-project-images/17.jpg' },
      { type: 'video', src: 'assets/3370-project-images/12.mp4' },
      { type: 'image', src: 'assets/3370-project-images/18.jpg' },
      { type: 'image', src: 'assets/3370-project-images/19.jpg' },
      { type: 'image', src: 'assets/3370-project-images/20.jpg' },
      { type: 'image', src: 'assets/3370-project-images/25.jpg' },
      { type: 'image', src: 'assets/3370-project-images/25.6.jpg' },
      { type: 'image', src: 'assets/3370-project-images/26.jpg' },
      { type: 'image', src: 'assets/3370-project-images/27.jpg' },
      { type: 'image', src: 'assets/3370-project-images/28.jpg' },
      { type: 'image', src: 'assets/3370-project-images/29.jpg' },
      { type: 'image', src: 'assets/3370-project-images/22.jpg' },
      { type: 'image', src: 'assets/3370-project-images/23.jpg' },
      { type: 'image', src: 'assets/3370-project-images/24.jpg' },
      { type: 'image', src: 'assets/3370-project-images/framing-interior-ladder-2%20copy%202.jpg' },
      { type: 'image', src: 'assets/3370-project-images/30.jpg' },
      { type: 'image', src: 'assets/3370-project-images/IMG_3080.jpg' },
      { type: 'image', src: 'assets/3370-project-images/IMG_3081.jpg' },
      { type: 'image', src: 'assets/3370-project-images/IMG_3127.jpg' },
      { type: 'image', src: 'assets/3370-project-images/IMG_3128.jpg' },
      { type: 'image', src: 'assets/3370-project-images/IMG_3139.jpg' },
      { type: 'image', src: 'assets/3370-project-images/brimely%20finished.jpg' },
    ],
  },

  'orange-dental': {
    id: 'orange-dental',
    eyebrow: 'Residential',
    detailEyebrow: 'Commercial Dental',
    address: 'Orange Dental',
    titleLong: 'Orange Dental.',
    cardImage: 'assets/orange dental cover.PNG',
    isCutout: true,
    heroImage: 'assets/orange-dental-exterior.jpg',
    cardBlurb: "A residential build shaped around the homeowner's vision — bespoke cabinetry, custom casework, and tight finish work.",
    lede: 'A full commercial fit-out for a modern dental practice — bespoke cabinetry, reception joinery, and treatment-room millwork designed to hold up to daily clinical use.',
    narrative: {
      heading: 'Project Overview',
      paragraphs: [
        'Orange Dental came to KCW with a simple ask: a clinic that looks nothing like a clinic. Most dental offices default to sterile, oversized corporate furniture — they wanted a space that felt calm, considered, and architectural from the moment a patient walked in.',
        'We handled the full scope of the millwork package: reception casework, operatory cabinetry, storage built-ins, and finish carpentry throughout the practice. Every piece was milled in our shop, colour-matched to the interior palette, and installed by the same crew that built it.',
        'The result is a dental office that reads as warm and grounded — while still doing the hard job of standing up to daily clinical traffic, sterilization protocols, and years of patient throughput.',
      ],
    },
    specs: {
      heading: 'Project Specs',
      items: [
        { label: 'Location',  value: 'Greater Toronto Area' },
        { label: 'Scope',     value: 'Commercial dental clinic fit-out' },
        { label: 'Materials', value: 'Engineered veneers, solid hardwood trim, stone-clad casework' },
        { label: 'Features',  value: 'Custom reception desk, operatory cabinetry, integrated storage' },
        { label: 'Status',    value: 'Completed & open' },
      ],
    },
    cta: {
      heading: 'Planning A Clinic Or Commercial Space?',
      body: 'Dental offices, retail, hospitality — we handle the full fit-out under one roof.',
      label: 'Start A Project',
    },
    metaDescription: 'KCW Project — Orange Dental. Commercial dental clinic fit-out with custom cabinetry and millwork.',
    gallery: [
      { type: 'image', src: 'assets/orange-dental-album/IMG_3596.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3597.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3599.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3600.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3601.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3602.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3603.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3604.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3605.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3606.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3607.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3608.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3609.jpg' },
      { type: 'image', src: 'assets/orange-dental-album/IMG_3610.jpg' },
    ],
  },

  government: {
    id: 'government',
    eyebrow: 'Structural',
    detailEyebrow: 'Structural',
    address: 'Ramada Hotel',
    titleLong: 'Ramada Hotel.',
    cardImage: 'assets/ramada project.jpg',
    isCutout: true,
    heroImage: 'assets/ramada project.jpg',
    cardBlurb: 'Structural framing and rough carpentry delivered to spec — on time, on budget, and inspection-ready.',
    lede: 'Structural framing and rough carpentry delivered to spec — on time, on budget, and inspection-ready from the first walk-through.',
    narrative: {
      heading: 'Project Overview',
      paragraphs: [
        'Structural work is where careful planning meets honest labour. Ramada Hotel was a full framing package: floors, walls, roof system, and the engineered connections that make it all hold together through a decade of Ontario winters.',
        "KCW's crew handled framing end-to-end, coordinating directly with the structural engineer and the site supervisor so nothing got lost between the drawings and the wood. Inspectors came, inspectors signed off — first pass.",
        "Good framing isn't glamorous work. But every finished space that follows depends on it being done right the first time.",
      ],
    },
    specs: {
      heading: 'Project Specs',
      items: [
        { label: 'Location',  value: 'Ramada Hotel, Greater Toronto Area' },
        { label: 'Scope',     value: 'Structural framing & rough carpentry' },
        { label: 'Materials', value: 'Engineered lumber, dimensional framing' },
        { label: 'Delivered', value: 'In-house crew, licensed and insured' },
        { label: 'Status',    value: 'Completed — inspection passed' },
      ],
    },
    cta: {
      heading: 'Got A Structural Build Coming Up?',
      body: "Send us the drawings — we'll tell you what it really takes to build it right.",
      label: 'Request A Quote',
    },
    metaDescription: 'KCW Project — Ramada Hotel. Structural framing and rough carpentry delivered to code.',
  },

  skyridge: {
    id: 'skyridge',
    eyebrow: 'Wall Paneling',
    detailEyebrow: 'Wall Paneling',
    address: '1100 Skyridge Blvd',
    titleLong: '1100 Skyridge Blvd.',
    cardImage: 'assets/PREMIUMOUTDOOR LIVING.jpg',
    isCutout: true,
    heroImage: 'assets/1100 skyridge blvd.JPG',
    cardBlurb: 'Bespoke wall paneling and slat treatments milled in-house and installed by the KCW crew.',
    lede: 'Bespoke wall paneling and slat treatments — milled in-house, colour-matched to the space, and installed by the same crew that built them.',
    narrative: {
      heading: 'Project Overview',
      paragraphs: [
        'Wall paneling can go one of two ways: a trend that dates the room in three years, or a design move that makes the whole space feel considered. At 1100 Skyridge, we went for the second.',
        'KCW drew the slat profile, milled the panels, finished them to the interior scheme, and handled every cut on site. The spacing, the rhythm, the transitions at the ceiling and floor — nothing was left to improvisation.',
        'The result is a surface that holds up close and reads well from the other side of the room.',
      ],
    },
    specs: {
      heading: 'Project Specs',
      items: [
        { label: 'Location',  value: '1100 Skyridge Blvd, Greater Toronto Area' },
        { label: 'Scope',     value: 'Wall paneling & slat treatments' },
        { label: 'Materials', value: 'Solid hardwood slats, veneered backing' },
        { label: 'Delivered', value: 'Custom milled and installed in-house' },
        { label: 'Status',    value: 'Completed' },
      ],
    },
    cta: {
      heading: 'Thinking About Paneling Or A Feature Wall?',
      body: "Send us the room — we'll come back with a profile and a plan.",
      label: 'Start A Project',
    },
    metaDescription: 'KCW Project — 1100 Skyridge Blvd. Bespoke wall paneling and slat treatments.',
  },
};
